name: 'Iwtem release action'
description: 'A GitHub action that help you publish release'
author: 'iwtem'
branding:
  icon: 'layers'
  color: 'orange'
inputs:
  triger:
    required: true
    description: '如何触发 Action'
  branch:
    required: true
    description: 'Changelogs 的 所在分支'
  changelogs:
    required: true
    description: 'Changelogs 的文件名称'
  token:
    required: false
    default: ${{ github.token }}
    description: 'GitHub token'
  prettier:
    required: false
    description: '是否需要进行美化 changelog'
  prerelease-flags:
    required: false
    description: '发布 prerelease 的标志'
runs:
  using: node12
  main: 'dist/index.js'
